server:
  port: 8096

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: post-service
  config:
    import: optional:configserver:config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    stream:
      function:
        definition: createdUserConsumer
      kafka:
        binder:
          brokers: "localhost:29092"
          replicationFactor: 1
      bindings:
        createdUserConsumer-in-0:
          destination: "user-created"
          content-type: application/json